# serverless.yml

service: my-express-application

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: false
    packager: 'npm'   # Packager that will be used to package your external modules
    #excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  bundle:
    linting: false
    tsConfig: 'tsconfig.json'
  serverless-offline:
    httpPort: ${opt:port, 3001}
    noPrependStageInUrl: true

package:
  individually: false
  excludeDevDependencies: false

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  endpointType: EDGE
  lambdaHashingVersion: 20201221
  memorySize: 3008
  timeout: 900
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
